# Generated by Django 4.2.7 on 2023-11-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('image_url', models.CharField(max_length=128)),
                ('hovered_image_url', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='CatBreed',
        ),
    ]
