# Generated by Django 4.2.7 on 2024-01-12 13:14

from django.db import migrations, models
import restapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_product_created_at_product_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hovered_image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='hovered_image',
            field=models.ImageField(blank=True, null=True, upload_to=restapi.models.get_product_images_upload_location),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restapi.models.get_product_images_upload_location),
        ),
    ]
