# Generated by Django 4.2.7 on 2024-01-21 13:36

from django.db import migrations, models
import restapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_alter_product_hovered_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hovered_image',
            field=models.ImageField(blank=True, null=True, upload_to=restapi.models.get_product_images_upload_location),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restapi.models.get_product_images_upload_location),
        ),
    ]
