# Generated by Django 4.2.7 on 2024-01-24 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restapi.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0007_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.CharField(choices=[("Men's", 'MEN'), ("Women's", 'WOMEN'), ("Kid's", 'KID')], max_length=32),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=restapi.models.get_product_gallery_upload_location),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AWAITING CONFIRMATION', 'AWAITING_CONFIRMATION'), ('PAYED', 'PAYED'), ('CONFIRMED', 'CONFIRMED'), ('IN PROCESSING', 'IN_PROCESSING'), ('SEND', 'SEND'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('RETURN', 'RETURN')], max_length=32)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='orders', to='restapi.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
