# Generated by Django 4.2.7 on 2024-01-24 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='restapi.product', verbose_name='sizes'),
        ),
    ]
